
import java.awt.Color;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class FacturaGUI extends javax.swing.JFrame {

    /**
     * Creates new form FacturaGUI
     */
    public FacturaGUI() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nfactura = new javax.swing.JLabel();
        NfacturaTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        NombreTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ApellidosTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CalleTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        CiudadTF = new javax.swing.JTextField();
        ConseptoTl = new javax.swing.JLabel();
        ConseptoTF0 = new javax.swing.JTextField();
        PrecioTF0 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ConseptoTF1 = new javax.swing.JTextField();
        PrecioTF1 = new javax.swing.JTextField();
        ConseptoTF2 = new javax.swing.JTextField();
        PrecioTF2 = new javax.swing.JTextField();
        ConseptoTF3 = new javax.swing.JTextField();
        PrecioTF3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObservacionesTX = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        TotalTL = new javax.swing.JLabel();
        CpTF = new javax.swing.JTextField();
        ErrorTL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nfactura.setText("Nª Factura:");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Nombre.setText("Nombre:");

        jLabel1.setText("Apellidos:");

        jLabel2.setText("Calle:");

        jLabel3.setText("CP:");

        jLabel4.setText("Ciudad:");

        ConseptoTl.setText("Consepto:");

        jLabel5.setText("Precio:");

        jLabel6.setText("Observaciones:");

        ObservacionesTX.setColumns(20);
        ObservacionesTX.setRows(5);
        jScrollPane1.setViewportView(ObservacionesTX);

        jLabel7.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(Nfactura)
                                    .addComponent(Nombre))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ApellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(NfacturaTF))
                                            .addComponent(NombreTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ErrorTL, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(CiudadTF)
                                            .addComponent(CalleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ConseptoTF0, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ConseptoTl))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(PrecioTF0, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ConseptoTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(PrecioTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ConseptoTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(PrecioTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7)
                                                .addComponent(ConseptoTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(PrecioTF3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                                .addComponent(TotalTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(jScrollPane1))))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NfacturaTF)
                            .addComponent(Nfactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre)
                            .addComponent(NombreTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ErrorTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ApellidosTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalleTF)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(CpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CiudadTF))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConseptoTl)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConseptoTF0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioTF0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConseptoTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConseptoTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConseptoTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TotalTL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
        
        Factura f = new Factura();
        
        //Comprueba si el textField con nombre NfacturaTF tiene algun dato
        // y pasa el varlor de textfield a objet Factura
            if (NfacturaTF.getText().length()==0) {
                NfacturaTF.setBackground(Color.PINK);
              }else {
                f.NumeroFactura = NfacturaTF.getText();
                NfacturaTF.setBackground(Color.WHITE);
            }
        //Comprueba si el textField con nombre NombreTF tiene algun dato
        // y pasa el varlor de textfield a objet Factura
            if (NombreTF.getText().length()==0) {
                NombreTF.setBackground(Color.PINK);
            }else{
            f.Nombre = NombreTF.getText();
            NombreTF.setBackground(Color.WHITE);
            }
        //Comprueba si el textField con nombre ApellidosTF tiene algun dato
        // y pasa el varlor de textfield a objet Factura    
            if (ApellidosTF.getText().length()==0) {
               ApellidosTF.setBackground(Color.PINK);
            }else{
                f.Apellidos = ApellidosTF.getText();
                ApellidosTF.setBackground(Color.white);
            }
        //Comprueba si el textField con nombre CalleTf tiene algun dato
        // y pasa el varlor de textfield a objet Factura        
            if (CalleTF.getText().length()==0) {
                CalleTF.setBackground(Color.PINK);
             }else{
                f.Calle = CalleTF.getText();
                CalleTF.setBackground(Color.white);
            }
            
        //Comprueba si el textField con nombre CpTf tiene algun dato
        // y pasa el varlor de textfield a objet Factura    
            if (CpTF.getText().length()==0) {
                  CpTF.setBackground(Color.PINK);
            }else{
                 f.CP = Integer.valueOf(CpTF.getText()); 
                  System.out.println(f.CP);
                  CpTF.setBackground(Color.white);    
            }
        //Comprueba si el textField con nombre CiudadTF tiene algun dato
        // y pasa el varlor de textfield a objet Factura       
            if (CiudadTF.getText().length()==0) {
                CiudadTF.setBackground(Color.PINK);
            }else{
                f.Ciudad = CiudadTF.getText();
                CiudadTF.setBackground(Color.white);
            }
                  
            if (CiudadTF.getText().length()==0) {
                CiudadTF.setBackground(Color.PINK);
            }else{
                f.Ciudad = CiudadTF.getText();
                CiudadTF.setBackground(Color.white);
            }           
//01
            if (ConseptoTF0.getText().length() ==0 ) {
            ConseptoTF0.setBackground(Color.PINK);
        }else{
                f.ConseptoTF0 = ConseptoTF0.getName();
                ConseptoTF0.setBackground(Color.WHITE);
            }
            if (PrecioTF0.getText().length() == 0 ) {
            PrecioTF0.setBackground(Color.PINK);
        }else{
                f.PrecioTF0 = Integer.getInteger(PrecioTF0.getText());
                PrecioTF0.setBackground(Color.white);
            } 
//02
             if (ConseptoTF1.getText().length() ==0 ) {
            ConseptoTF1.setBackground(Color.PINK);
        }else{
                f.ConseptoTF1 = ConseptoTF0.getName();
                ConseptoTF1.setBackground(Color.WHITE);
            }
            if (PrecioTF1.getText().length() == 0 ) {
            PrecioTF1.setBackground(Color.PINK);
        }else{
                f.PrecioTF1 = Integer.getInteger(PrecioTF1.getText());
                PrecioTF0.setBackground(Color.white);
            }
//03
             if (ConseptoTF2.getText().length() ==0 ) {
            ConseptoTF2.setBackground(Color.PINK);
        }else{
                f.ConseptoTF2 = ConseptoTF2.getName();
                ConseptoTF2.setBackground(Color.WHITE);
            }
            if (PrecioTF2.getText().length() == 0 ) {
            PrecioTF2.setBackground(Color.PINK);
        }else{
                f.PrecioTF2 = Integer.getInteger(PrecioTF2.getText());
                PrecioTF2.setBackground(Color.white);
            }
//04
             if (ConseptoTF3.getText().length() ==0 ) {
            ConseptoTF3.setBackground(Color.PINK);
        }else{
                f.ConseptoTF3 = ConseptoTF3.getName();
                ConseptoTF3.setBackground(Color.WHITE);
            }
            if (PrecioTF3.getText().length() == 0 ) {
            PrecioTF3.setBackground(Color.PINK);
        }else{
                f.PrecioTF3 = Integer.getInteger(PrecioTF3.getText());
                PrecioTF3.setBackground(Color.white);
            }
    
        //Comprueba si todos los Fields estan con datos     
            if (NfacturaTF.getText().length()>=3 && NombreTF.getText().length()>=3 && ApellidosTF.getText().length()>=3 && CalleTF.getText().length()>=3 && CiudadTF.getText().length()>=3 && CpTF.getText().length() >=4 ) {
            
            ObservacionesTX.setText("Nº Factura:"   +f.NumeroFactura+"\nNombre: "+f.Nombre+"\nApellidos:    "+f.Apellidos+"\nCalle:   "+f.Calle+" CP: "+f.CP+"\nCiudad: "+f.Ciudad);
             
        }else{
                ErrorTL.setText("Rellena los campos en Color");
             NfacturaTF.setBackground(Color.WHITE);
            }
            
                    
                    
            
            
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosTF;
    private javax.swing.JTextField CalleTF;
    private javax.swing.JTextField CiudadTF;
    private javax.swing.JTextField ConseptoTF0;
    private javax.swing.JTextField ConseptoTF1;
    private javax.swing.JTextField ConseptoTF2;
    private javax.swing.JTextField ConseptoTF3;
    private javax.swing.JLabel ConseptoTl;
    private javax.swing.JTextField CpTF;
    private javax.swing.JLabel ErrorTL;
    private javax.swing.JLabel Nfactura;
    private javax.swing.JTextField NfacturaTF;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreTF;
    private javax.swing.JTextArea ObservacionesTX;
    private javax.swing.JTextField PrecioTF0;
    private javax.swing.JTextField PrecioTF1;
    private javax.swing.JTextField PrecioTF2;
    private javax.swing.JTextField PrecioTF3;
    private javax.swing.JLabel TotalTL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
