/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Menu00 extends javax.swing.JFrame {

    /**
     * Creates new form Menu00
     */
    public Menu00() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem15 = new javax.swing.JMenuItem();
        MenuPrincipal = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        NewProject = new javax.swing.JMenuItem();
        NewFile = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        OpenProject = new javax.swing.JMenuItem();
        OpenRecientProjectMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ClaseAirTextNew = new javax.swing.JMenuItem();
        OpenFile = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        SetMainProjectMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        AirTextNewProparties = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        Save = new javax.swing.JMenuItem();
        SaveAll = new javax.swing.JMenuItem();
        RefreshAllFile = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        PageSetup = new javax.swing.JMenuItem();
        Print = new javax.swing.JMenuItem();
        PrintHTML = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        undo = new javax.swing.JMenuItem();
        Redo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Cut = new javax.swing.JMenuItem();
        Copy = new javax.swing.JMenuItem();
        Paste = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        SelectAll = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        FindInTishPage = new javax.swing.JMenuItem();
        FindAgin = new javax.swing.JMenuItem();
        FindPrevious = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        FillInForm = new javax.swing.JMenuItem();
        SaveFormInfo = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        Preferences = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        Go = new javax.swing.JMenu();
        Bookmarks = new javax.swing.JMenu();
        Tools = new javax.swing.JMenu();
        Windows = new javax.swing.JMenu();
        Help = new javax.swing.JMenu();

        jMenuItem15.setText("jMenuItem15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        File.setText("File");
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        NewProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        NewProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1493601045_files-o.png"))); // NOI18N
        NewProject.setText("New Poject");
        NewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProjectActionPerformed(evt);
            }
        });
        File.add(NewProject);

        NewFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-o-16.png"))); // NOI18N
        NewFile.setText("New File..");
        NewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFileActionPerformed(evt);
            }
        });
        File.add(NewFile);
        File.add(jSeparator6);

        OpenProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        OpenProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpFile.png"))); // NOI18N
        OpenProject.setText("Open Project...");
        File.add(OpenProject);

        OpenRecientProjectMenu.setText("Open Recient Project");

        jMenuItem1.setText("Vasio");
        OpenRecientProjectMenu.add(jMenuItem1);

        File.add(OpenRecientProjectMenu);

        ClaseAirTextNew.setText("Clase \"AirText_New");
        ClaseAirTextNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaseAirTextNewActionPerformed(evt);
            }
        });
        File.add(ClaseAirTextNew);

        OpenFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenFile.setText("Open File");
        File.add(OpenFile);
        File.add(jSeparator7);

        SetMainProjectMenu.setText("Set Main Project");

        jMenuItem2.setText("Vasioo");
        SetMainProjectMenu.add(jMenuItem2);

        File.add(SetMainProjectMenu);

        AirTextNewProparties.setText("\"AirText_New\" Proparties");
        AirTextNewProparties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirTextNewPropartiesActionPerformed(evt);
            }
        });
        File.add(AirTextNewProparties);
        File.add(jSeparator9);

        Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Save.setText("Save");
        Save.setEnabled(false);
        File.add(Save);

        SaveAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        SaveAll.setText("Save All ");
        SaveAll.setEnabled(false);
        File.add(SaveAll);

        RefreshAllFile.setText("Refresh all File");
        File.add(RefreshAllFile);
        File.add(jSeparator10);

        PageSetup.setText("Page Setup...");
        File.add(PageSetup);

        Print.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Print.setText("Print...");
        Print.setEnabled(false);
        File.add(Print);

        PrintHTML.setText("Print to HTML...");
        PrintHTML.setEnabled(false);
        File.add(PrintHTML);
        File.add(jSeparator8);

        Exit.setText("Exit");
        File.add(Exit);

        MenuPrincipal.add(File);

        Edit.setText("Edit");

        undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.META_MASK));
        undo.setText("Undo");
        undo.setToolTipText("");
        undo.setEnabled(false);
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });
        Edit.add(undo);

        Redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.META_MASK));
        Redo.setText("Redo");
        Redo.setEnabled(false);
        Edit.add(Redo);
        Edit.add(jSeparator1);

        Cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.META_MASK));
        Cut.setText("Cut");
        Cut.setEnabled(false);
        Edit.add(Cut);

        Copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.META_MASK));
        Copy.setText("Copy");
        Copy.setEnabled(false);
        Edit.add(Copy);

        Paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.META_MASK));
        Paste.setText("Paste");
        Edit.add(Paste);

        Delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.META_MASK));
        Delete.setText("Delete");
        Delete.setEnabled(false);
        Edit.add(Delete);
        Edit.add(jSeparator2);

        SelectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.META_MASK));
        SelectAll.setText("Select All");
        Edit.add(SelectAll);
        Edit.add(jSeparator3);

        FindInTishPage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.META_MASK));
        FindInTishPage.setText("Find in Tish page..");
        Edit.add(FindInTishPage);

        FindAgin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.META_MASK));
        FindAgin.setText("Find Agin");
        FindAgin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindAginActionPerformed(evt);
            }
        });
        Edit.add(FindAgin);

        FindPrevious.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.META_MASK));
        FindPrevious.setText("Find Previous");
        FindPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindPreviousActionPerformed(evt);
            }
        });
        Edit.add(FindPrevious);
        Edit.add(jSeparator4);

        FillInForm.setText("Fill in Form");
        FillInForm.setEnabled(false);
        Edit.add(FillInForm);

        SaveFormInfo.setText("Save Form Info");
        SaveFormInfo.setEnabled(false);
        Edit.add(SaveFormInfo);
        Edit.add(jSeparator5);

        Preferences.setText("Preferences...");
        Edit.add(Preferences);

        MenuPrincipal.add(Edit);

        View.setText("View");
        MenuPrincipal.add(View);

        Go.setText("Go");
        MenuPrincipal.add(Go);

        Bookmarks.setText("Bookmarks");
        MenuPrincipal.add(Bookmarks);

        Tools.setText("Tools");
        MenuPrincipal.add(Tools);

        Windows.setText("Windows");
        MenuPrincipal.add(Windows);

        Help.setText("Help");
        MenuPrincipal.add(Help);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FindAginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindAginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindAginActionPerformed

    private void FindPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindPreviousActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undoActionPerformed

    private void NewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewProjectActionPerformed

    private void NewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewFileActionPerformed

    private void ClaseAirTextNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaseAirTextNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClaseAirTextNewActionPerformed

    private void AirTextNewPropartiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirTextNewPropartiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirTextNewPropartiesActionPerformed

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu00.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu00.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu00.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu00.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu00().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AirTextNewProparties;
    private javax.swing.JMenu Bookmarks;
    private javax.swing.JMenuItem ClaseAirTextNew;
    private javax.swing.JMenuItem Copy;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem FillInForm;
    private javax.swing.JMenuItem FindAgin;
    private javax.swing.JMenuItem FindInTishPage;
    private javax.swing.JMenuItem FindPrevious;
    private javax.swing.JMenu Go;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem NewFile;
    private javax.swing.JMenuItem NewProject;
    private javax.swing.JMenuItem OpenFile;
    private javax.swing.JMenuItem OpenProject;
    private javax.swing.JMenu OpenRecientProjectMenu;
    private javax.swing.JMenuItem PageSetup;
    private javax.swing.JMenuItem Paste;
    private javax.swing.JMenuItem Preferences;
    private javax.swing.JMenuItem Print;
    private javax.swing.JMenuItem PrintHTML;
    private javax.swing.JMenuItem Redo;
    private javax.swing.JMenuItem RefreshAllFile;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem SaveAll;
    private javax.swing.JMenuItem SaveFormInfo;
    private javax.swing.JMenuItem SelectAll;
    private javax.swing.JMenu SetMainProjectMenu;
    private javax.swing.JMenu Tools;
    private javax.swing.JMenu View;
    private javax.swing.JMenu Windows;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem undo;
    // End of variables declaration//GEN-END:variables
}
