
import java.awt.Color;
import static java.awt.image.ImageObserver.HEIGHT;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ContabilidadGUI extends javax.swing.JFrame {

    /**
     * Creates new form FacturaGUI
     */
    public ContabilidadGUI() {
        initComponents();
        BuscarFactura.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Nfactura = new javax.swing.JLabel();
        NfacturaTF = new javax.swing.JTextField();
        VerFacturaCompleta = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        NombreTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ApellidosTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CalleTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        CiudadTF = new javax.swing.JTextField();
        ConseptoTl = new javax.swing.JLabel();
        ConseptoTF0 = new javax.swing.JTextField();
        PrecioTF0 = new javax.swing.JTextField();
        PrecioTF = new javax.swing.JLabel();
        ConseptoTF1 = new javax.swing.JTextField();
        PrecioTF1 = new javax.swing.JTextField();
        ConseptoTF2 = new javax.swing.JTextField();
        PrecioTF2 = new javax.swing.JTextField();
        ConseptoTF3 = new javax.swing.JTextField();
        PrecioTF3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObservacionesTF = new javax.swing.JTextArea();
        CpTF = new javax.swing.JTextField();
        nombreRB = new javax.swing.JRadioButton();
        nFacturaRB = new javax.swing.JRadioButton();
        ErrorTL = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        GuardarTodo = new javax.swing.JButton();
        BuscarFactura = new javax.swing.JButton();
        MensajeTF = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Top = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        GuardarFacturaMenu = new javax.swing.JMenuItem();
        BuscarMunu = new javax.swing.JMenuItem();
        CargarUltimaFacturaMenu = new javax.swing.JMenuItem();
        LimpiarPantallaMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        SalirMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Factura Tattoo Ink Valladolid ");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(50, 50, 50));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(523, 705));
        setMinimumSize(new java.awt.Dimension(523, 705));
        getContentPane().setLayout(null);

        Nfactura.setText("Nª Factura:");
        getContentPane().add(Nfactura);
        Nfactura.setBounds(44, 14, 70, 16);
        getContentPane().add(NfacturaTF);
        NfacturaTF.setBounds(120, 10, 105, 24);

        VerFacturaCompleta.setText("Ver ultima Factura");
        VerFacturaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerFacturaCompletaActionPerformed(evt);
            }
        });
        getContentPane().add(VerFacturaCompleta);
        VerFacturaCompleta.setBounds(340, 620, 144, 32);

        Nombre.setText("Nombre:");
        getContentPane().add(Nombre);
        Nombre.setBounds(44, 48, 54, 16);
        getContentPane().add(NombreTF);
        NombreTF.setBounds(120, 44, 242, 24);

        jLabel1.setText("Apellidos:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(44, 78, 63, 16);
        getContentPane().add(ApellidosTF);
        ApellidosTF.setBounds(120, 74, 364, 24);

        jLabel2.setText("Ciudad:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(44, 138, 48, 16);
        getContentPane().add(CalleTF);
        CalleTF.setBounds(120, 104, 214, 24);

        jLabel3.setText("CP:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 108, 20, 16);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(44, 183, 440, 12);

        jLabel4.setText("Calle:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(44, 108, 35, 16);
        getContentPane().add(CiudadTF);
        CiudadTF.setBounds(120, 134, 364, 24);

        ConseptoTl.setText("Consepto:               Al menos uno obligatorio");
        getContentPane().add(ConseptoTl);
        ConseptoTl.setBounds(44, 202, 284, 16);

        ConseptoTF0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConseptoTF0ActionPerformed(evt);
            }
        });
        getContentPane().add(ConseptoTF0);
        ConseptoTF0.setBounds(44, 224, 324, 24);
        getContentPane().add(PrecioTF0);
        PrecioTF0.setBounds(393, 224, 91, 24);

        PrecioTF.setText("Precio:");
        getContentPane().add(PrecioTF);
        PrecioTF.setBounds(393, 202, 42, 16);
        getContentPane().add(ConseptoTF1);
        ConseptoTF1.setBounds(44, 254, 324, 24);
        getContentPane().add(PrecioTF1);
        PrecioTF1.setBounds(393, 254, 91, 24);
        getContentPane().add(ConseptoTF2);
        ConseptoTF2.setBounds(44, 284, 324, 24);
        getContentPane().add(PrecioTF2);
        PrecioTF2.setBounds(393, 284, 91, 24);
        getContentPane().add(ConseptoTF3);
        ConseptoTF3.setBounds(44, 314, 324, 24);
        getContentPane().add(PrecioTF3);
        PrecioTF3.setBounds(393, 314, 91, 24);

        ObservacionesTF.setColumns(20);
        ObservacionesTF.setRows(5);
        jScrollPane1.setViewportView(ObservacionesTF);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(44, 380, 440, 239);
        getContentPane().add(CpTF);
        CpTF.setBounds(372, 104, 112, 24);

        buttonGroup1.add(nombreRB);
        nombreRB.setText("Nombre");
        nombreRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRBActionPerformed(evt);
            }
        });
        getContentPane().add(nombreRB);
        nombreRB.setBounds(320, 10, 84, 25);

        buttonGroup1.add(nFacturaRB);
        nFacturaRB.setText("N-Factura");
        nFacturaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nFacturaRBActionPerformed(evt);
            }
        });
        getContentPane().add(nFacturaRB);
        nFacturaRB.setBounds(230, 10, 110, 25);
        getContentPane().add(ErrorTL);
        ErrorTL.setBounds(527, 342, 17, 32);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(44, 625, 57, 32);

        GuardarTodo.setText("Guardar");
        GuardarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarTodo);
        GuardarTodo.setBounds(250, 620, 79, 32);

        BuscarFactura.setText("Buscar ");
        BuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarFactura);
        BuscarFactura.setBounds(400, 10, 80, 32);

        MensajeTF.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(MensajeTF);
        MensajeTF.setBounds(180, 350, 299, 24);

        jLabel6.setText("Observaciones");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(53, 358, 92, 16);
        getContentPane().add(Top);
        Top.setBounds(290, 164, 37, 13);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Office 30 Porcen.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-480, 0, 1140, 730);

        jMenu1.setText("Archivo");

        GuardarFacturaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
        GuardarFacturaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuevoArchivo.png"))); // NOI18N
        GuardarFacturaMenu.setText("Guardar Factura");
        GuardarFacturaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarFacturaMenuActionPerformed(evt);
            }
        });
        jMenu1.add(GuardarFacturaMenu);

        BuscarMunu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.META_MASK));
        BuscarMunu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa-para-buscar.png"))); // NOI18N
        BuscarMunu.setText("Buscar Factura");
        BuscarMunu.setEnabled(false);
        BuscarMunu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMunuActionPerformed(evt);
            }
        });
        jMenu1.add(BuscarMunu);

        CargarUltimaFacturaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.META_MASK));
        CargarUltimaFacturaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marca-de-cargando.png"))); // NOI18N
        CargarUltimaFacturaMenu.setText("Cargar Ultima Factura");
        CargarUltimaFacturaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarUltimaFacturaMenuActionPerformed(evt);
            }
        });
        jMenu1.add(CargarUltimaFacturaMenu);

        LimpiarPantallaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.META_MASK));
        LimpiarPantallaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escobilla-de-suelo.png"))); // NOI18N
        LimpiarPantallaMenu.setText("Limpiar patilla");
        LimpiarPantallaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarPantallaMenuActionPerformed(evt);
            }
        });
        jMenu1.add(LimpiarPantallaMenu);
        jMenu1.add(jSeparator2);

        SalirMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        SalirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida.png"))); // NOI18N
        SalirMenu.setText("Salir");
        SalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMenuActionPerformed(evt);
            }
        });
        jMenu1.add(SalirMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerFacturaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerFacturaCompletaActionPerformed
Factura dataFactura = new Factura();
        //condiciones de texto en blanco
        //Recojer datos de todos los campos de texto
         if (NfacturaTF.getText().equals("")) {
            NfacturaTF.setBackground(Color.pink);
            }else{
            NfacturaTF.setBackground(Color.WHITE);
            dataFactura.numeroFactura = NfacturaTF.getText();
        }
         
        if (NombreTF.getText().equals("")) {
            NombreTF.setBackground(Color.pink);
            }else{
            NombreTF.setBackground(Color.WHITE);
            dataFactura.nombre = NombreTF.getText();
        }
        
        if (ApellidosTF.getText().equals("")) {
            ApellidosTF.setBackground(Color.pink);
            }else{
            ApellidosTF.setBackground(Color.WHITE);
            dataFactura.apellidos = ApellidosTF.getText();
        }
        
        if (CalleTF.getText().equals("")) {
            CalleTF.setBackground(Color.pink);
            }else{
            CalleTF.setBackground(Color.WHITE);
            dataFactura.calle = CalleTF.getText();
        }
         
        if (CpTF.getText().equals("")) {
            CpTF.setBackground(Color.pink);
            }else{
            CpTF.setBackground(Color.WHITE);
            dataFactura.cP = CpTF.getText();
        }
         
        if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
        
        if (ConseptoTF0.getText().equals("")) {
            ConseptoTF0.setBackground(Color.pink);
            }else{
            ConseptoTF0.setBackground(Color.WHITE);
            dataFactura.conseptoTF0 = ConseptoTF0.getText();
        }
        
        if (ConseptoTF1.getText().equals("")) {
            ConseptoTF1.setBackground(Color.pink);
            }else{
            ConseptoTF1.setBackground(Color.WHITE);
            dataFactura.conseptoTF1 = ConseptoTF1.getText();
        }
         
        if (ConseptoTF2.getText().equals("")) {
            ConseptoTF2.setBackground(Color.pink);
            }else{
            ConseptoTF2.setBackground(Color.WHITE);
            dataFactura.conseptoTF2 = ConseptoTF2.getText();
        }
        
        if (ConseptoTF3.getText().equals("")) {
            ConseptoTF3.setBackground(Color.pink);
            }else{
            ConseptoTF3.setBackground(Color.WHITE);
            dataFactura.conseptoTF3 = ConseptoTF3.getText();
        }
        
        if (PrecioTF0.getText().equals("")) {
            PrecioTF0.setBackground(Color.pink);
            }else{
            PrecioTF0.setBackground(Color.WHITE);
            dataFactura.precioTF0 = PrecioTF0.getText();    
        }
         
        if (PrecioTF1.getText().equals("")) {
            PrecioTF1.setBackground(Color.pink);
            }else{
            PrecioTF1.setBackground(Color.white);
            dataFactura.precioTF1 = PrecioTF1.getText();
        }
         
        if (PrecioTF2.getText().equals("")) {
            PrecioTF2.setBackground(Color.pink);
            }else{
            PrecioTF2.setBackground(Color.white);
             dataFactura.precioTF2 = PrecioTF2.getText();
        }
           
        if (PrecioTF3.getText().equals("")) {
            PrecioTF3.setBackground(Color.pink);
            }else{
            PrecioTF3.setBackground(Color.pink);
            dataFactura.precioTF3 = PrecioTF3.getText();
        }
        if (ObservacionesTF.getText().equals("")) {
            ObservacionesTF.setBackground(Color.pink);
            }else{
            ObservacionesTF.setBackground(Color.white);
            dataFactura.observacionesTF = ObservacionesTF.getText();
        }
          
         
       
          if ( CiudadTF.getText().equals("") && CpTF.getText().equals("")
                && CalleTF.getText().equals("") && ApellidosTF.getText().equals("") 
                && NombreTF.getText().equals("") && NfacturaTF.getText().equals("") 
                && ConseptoTF0.getText().equals("") && PrecioTF0.getText().equals("")
                && ConseptoTF1.getText().equals("") && PrecioTF1.getText().equals("")
                && ConseptoTF2.getText().equals("") && PrecioTF2.getText().equals("")
                && ConseptoTF3.getText().equals("") && PrecioTF3.getText().equals("")
            ){
            
             MensajeTF.setText("Rellena Todos los campos de color rosa");
            }else{
             //Abrir una nueva ventana 
        dispose();
        FacturaCompleta NuevaVentana = new FacturaCompleta();
        NuevaVentana.setVisible(true);
        }      
          
            
    }//GEN-LAST:event_VerFacturaCompletaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        
      JDialog.setDefaultLookAndFeelDecorated(true);
    int response = JOptionPane.showConfirmDialog(Top, "Quieres guardar antes de salir", "Mensaje Importante",
        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
    if (response == JOptionPane.NO_OPTION) {
      
      System.exit(0);
    } else if (response == JOptionPane.YES_OPTION) {
                 Factura dataFactura = new Factura();
        //condiciones de texto en blanco
        //Recojer datos de todos los campos de texto
         if (NfacturaTF.getText().equals("")) {
            NfacturaTF.setBackground(Color.pink);
            }else{
            NfacturaTF.setBackground(Color.WHITE);
            dataFactura.numeroFactura = NfacturaTF.getText();
        }
         
        if (NombreTF.getText().equals("")) {
            NombreTF.setBackground(Color.pink);
            }else{
            NombreTF.setBackground(Color.WHITE);
            dataFactura.nombre = NombreTF.getText();
        }
        
        if (ApellidosTF.getText().equals("")) {
            ApellidosTF.setBackground(Color.pink);
            }else{
            ApellidosTF.setBackground(Color.WHITE);
            dataFactura.apellidos = ApellidosTF.getText();
        }
        
        if (CalleTF.getText().equals("")) {
            CalleTF.setBackground(Color.pink);
            }else{
            CalleTF.setBackground(Color.WHITE);
            dataFactura.calle = CalleTF.getText();
        }
         
        if (CpTF.getText().equals("")) {
            CpTF.setBackground(Color.pink);
            }else{
            CpTF.setBackground(Color.WHITE);
            dataFactura.cP = CpTF.getText();
        }
         
        if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
        
         if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
         
         if (ConseptoTF0.getText().equals("")) {
            ConseptoTF0.setBackground(Color.pink);
            }else{
            ConseptoTF0.setBackground(Color.WHITE);
            dataFactura.conseptoTF0 = ConseptoTF0.getText();
        }
         
         if (ConseptoTF1.getText().equals("")) {
            ConseptoTF1.setBackground(Color.pink);
            }else{
            ConseptoTF1.setBackground(Color.WHITE);
            dataFactura.conseptoTF1 = ConseptoTF1.getText();
        }
         
        if (ConseptoTF2.getText().equals("")) {
            ConseptoTF2.setBackground(Color.pink);
            }else{
            ConseptoTF2.setBackground(Color.WHITE);
            dataFactura.conseptoTF2 = ConseptoTF2.getText();
        }
        
         if (ConseptoTF3.getText().equals("")) {
            ConseptoTF3.setBackground(Color.pink);
            }else{
            ConseptoTF3.setBackground(Color.WHITE);
            dataFactura.conseptoTF3 = ConseptoTF3.getText();
        }
        
        if (PrecioTF0.getText().equals("")) {
            PrecioTF0.setBackground(Color.pink);
            }else{
            PrecioTF0.setBackground(Color.WHITE);
            dataFactura.precioTF0 = PrecioTF0.getText();    
        }
         
        if (PrecioTF1.getText().equals("")) {
            PrecioTF1.setBackground(Color.pink);
            }else{
            PrecioTF1.setBackground(Color.white);
            dataFactura.precioTF1 = PrecioTF1.getText();
        }
        
        if (PrecioTF2.getText().equals("")) {
            PrecioTF2.setBackground(Color.pink);
            }else{
            PrecioTF2.setBackground(Color.white);
            dataFactura.precioTF2 = PrecioTF2.getText();
         }
        
        if (PrecioTF3.getText().equals("")) {
            PrecioTF3.setBackground(Color.pink);
            }else{
            PrecioTF3.setBackground(Color.white);
            dataFactura.precioTF3 = PrecioTF3.getText();
         }
        
        if (ObservacionesTF.getText().equals("")) {
            ObservacionesTF.setBackground(Color.pink);
            }else{
            ObservacionesTF.setBackground(Color.white);
            dataFactura.observacionesTF = ObservacionesTF.getText();
            }
        //Condicion para poder guardar. Campos obligatorios.
        if ( CiudadTF.getText().equals("") && CpTF.getText().equals("")
                && CalleTF.getText().equals("") && ApellidosTF.getText().equals("") 
                && NombreTF.getText().equals("") && NfacturaTF.getText().equals("") 
                && ConseptoTF0.getText().equals("") && PrecioTF1.getText().equals("")
            ){
            
            String multiLineMsg[] = { "Antes de guardar los campos color rosa", " Deven de estar rellenos" };
    JOptionPane pane = new JOptionPane();
    pane.setMessage(multiLineMsg);
    JDialog d = pane.createDialog(Top, "Informacion");
    d.setVisible(true);
   

           
            }else{
             //Guardar todos los datos en un archivo CSV
            Guardar guardar = new Guardar();
            guardar.guardarFactura(dataFactura.getFacturaCSV());
            
            System.exit(0);
        } 
    } else if (response == JOptionPane.CANCEL_OPTION) {
      //System.out.println("boton Cansel");
    } else if (response == JOptionPane.CLOSED_OPTION) {
     // System.out.println("boton x"); 
        }
        
    }//GEN-LAST:event_SalirActionPerformed

    private void GuardarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarTodoActionPerformed
        
        Factura dataFactura = new Factura();
        //condiciones de texto en blanco
        //Recojer datos de todos los campos de texto
         if (NfacturaTF.getText().equals("")) {
            NfacturaTF.setBackground(Color.pink);
            }else{
            NfacturaTF.setBackground(Color.WHITE);
            dataFactura.numeroFactura = NfacturaTF.getText();
        }
         
        if (NombreTF.getText().equals("")) {
            NombreTF.setBackground(Color.pink);
            }else{
            NombreTF.setBackground(Color.WHITE);
            dataFactura.nombre = NombreTF.getText();
        }
        
        if (ApellidosTF.getText().equals("")) {
            ApellidosTF.setBackground(Color.pink);
            }else{
            ApellidosTF.setBackground(Color.WHITE);
            dataFactura.apellidos = ApellidosTF.getText();
        }
        
        if (CalleTF.getText().equals("")) {
            CalleTF.setBackground(Color.pink);
            }else{
            CalleTF.setBackground(Color.WHITE);
            dataFactura.calle = CalleTF.getText();
        }
         
        if (CpTF.getText().equals("")) {
            CpTF.setBackground(Color.pink);
            }else{
            CpTF.setBackground(Color.WHITE);
            dataFactura.cP = CpTF.getText();
        }
         
        if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
        
         if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
         
         if (ConseptoTF0.getText().equals("")) {
            ConseptoTF0.setBackground(Color.pink);
            }else{
            ConseptoTF0.setBackground(Color.WHITE);
            dataFactura.conseptoTF0 = ConseptoTF0.getText();
        }
         
         if (ConseptoTF1.getText().equals("")) {
            ConseptoTF1.setBackground(Color.pink);
            }else{
            ConseptoTF1.setBackground(Color.WHITE);
            dataFactura.conseptoTF1 = ConseptoTF1.getText();
        }
         
        if (ConseptoTF2.getText().equals("")) {
            ConseptoTF2.setBackground(Color.pink);
            }else{
            ConseptoTF2.setBackground(Color.WHITE);
            dataFactura.conseptoTF2 = ConseptoTF2.getText();
        }
        
         if (ConseptoTF3.getText().equals("")) {
            ConseptoTF3.setBackground(Color.pink);
            }else{
            ConseptoTF3.setBackground(Color.WHITE);
            dataFactura.conseptoTF3 = ConseptoTF3.getText();
        }
        
        if (PrecioTF0.getText().equals("")) {
            PrecioTF0.setBackground(Color.pink);
            }else{
            PrecioTF0.setBackground(Color.WHITE);
            dataFactura.precioTF0 = PrecioTF0.getText();    
        }
         
        if (PrecioTF1.getText().equals("")) {
            PrecioTF1.setBackground(Color.pink);
            }else{
            PrecioTF1.setBackground(Color.white);
            dataFactura.precioTF1 = PrecioTF1.getText();
        }
        
        if (PrecioTF2.getText().equals("")) {
            PrecioTF2.setBackground(Color.pink);
            }else{
            PrecioTF2.setBackground(Color.white);
            dataFactura.precioTF2 = PrecioTF2.getText();
         }
        
        if (PrecioTF3.getText().equals("")) {
            PrecioTF3.setBackground(Color.pink);
            }else{
            PrecioTF3.setBackground(Color.white);
            dataFactura.precioTF3 = PrecioTF3.getText();
         }
        
        if (ObservacionesTF.getText().equals("")) {
            ObservacionesTF.setBackground(Color.pink);
            }else{
            ObservacionesTF.setBackground(Color.white);
            dataFactura.observacionesTF = ObservacionesTF.getText();
            }
        //Condicion para poder guardar. Campos obligatorios.
        if ( CiudadTF.getText().equals("") && CpTF.getText().equals("")
                && CalleTF.getText().equals("") && ApellidosTF.getText().equals("") 
                && NombreTF.getText().equals("") && NfacturaTF.getText().equals("") 
                && ConseptoTF0.getText().equals("") && PrecioTF1.getText().equals("")
            ){
            
             MensajeTF.setText("Rellena Todos los campos de color rosa");
            }else{
             //Guardar todos los datos en un archivo CSV
            Guardar guardar = new Guardar();
            guardar.guardarFactura(dataFactura.getFacturaCSV());
            MensajeTF.setText("");
        }      
    }//GEN-LAST:event_GuardarTodoActionPerformed

    private void BuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarFacturaActionPerformed
        
        if (nFacturaRB.isSelected()) {
        
             ArrayList<Factura> miFacturas = LeerArchivo.leerFacturas("todasFacturas.csv");
             for (Factura miFactura : miFacturas) {
               if (NfacturaTF.getText().equals(miFactura.numeroFactura)) {
                   
                   
                     NfacturaTF.setText(miFactura.numeroFactura);
               NombreTF.setText(miFactura.nombre);
               ApellidosTF.setText(miFactura.apellidos);
               CalleTF.setText(miFactura.calle);
               CpTF.setText(miFactura.cP);
               CiudadTF.setText(miFactura.ciudad);
               ConseptoTF0.setText(miFactura.conseptoTF0);
               ConseptoTF1.setText(miFactura.conseptoTF1);
               ConseptoTF2.setText(miFactura.conseptoTF2);
               ConseptoTF3.setText(miFactura.conseptoTF3);
               PrecioTF0.setText(miFactura.precioTF0);
               PrecioTF1.setText(miFactura.precioTF1);
               PrecioTF2.setText(miFactura.precioTF2);
               PrecioTF3.setText(miFactura.precioTF3);
               ObservacionesTF.setText(miFactura.observacionesTF);
               break;
               
               } 
               
            }   
        
        Factura dataFactura = new Factura();
        //condiciones de texto en blanco
        //Recojer datos de todos los campos de texto
         if (NfacturaTF.getText().equals("")) {
            NfacturaTF.setBackground(Color.pink);
            }else{
            NfacturaTF.setBackground(Color.WHITE);
            dataFactura.numeroFactura = NfacturaTF.getText();
        }
         
        if (NombreTF.getText().equals("")) {
            NombreTF.setBackground(Color.pink);
            }else{
            NombreTF.setBackground(Color.WHITE);
            dataFactura.nombre = NombreTF.getText();
        }
        
        if (ApellidosTF.getText().equals("")) {
            ApellidosTF.setBackground(Color.pink);
            }else{
            ApellidosTF.setBackground(Color.WHITE);
            dataFactura.apellidos = ApellidosTF.getText();
        }
        
        if (CalleTF.getText().equals("")) {
            CalleTF.setBackground(Color.pink);
            }else{
            CalleTF.setBackground(Color.WHITE);
            dataFactura.calle = CalleTF.getText();
        }
         
        if (CpTF.getText().equals("")) {
            CpTF.setBackground(Color.pink);
            }else{
            CpTF.setBackground(Color.WHITE);
            dataFactura.cP = CpTF.getText();
        }
         
        if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
        
         if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
         
         if (ConseptoTF0.getText().equals("")) {
            ConseptoTF0.setBackground(Color.pink);
            }else{
            ConseptoTF0.setBackground(Color.WHITE);
            dataFactura.conseptoTF0 = ConseptoTF0.getText();
        }
         
         if (ConseptoTF1.getText().equals("")) {
            ConseptoTF1.setBackground(Color.pink);
            }else{
            ConseptoTF1.setBackground(Color.WHITE);
            dataFactura.conseptoTF1 = ConseptoTF1.getText();
        }
         
        if (ConseptoTF2.getText().equals("")) {
            ConseptoTF2.setBackground(Color.pink);
            }else{
            ConseptoTF2.setBackground(Color.WHITE);
            dataFactura.conseptoTF2 = ConseptoTF2.getText();
        }
        
         if (ConseptoTF3.getText().equals("")) {
            ConseptoTF3.setBackground(Color.pink);
            }else{
            ConseptoTF3.setBackground(Color.WHITE);
            dataFactura.conseptoTF3 = ConseptoTF3.getText();
        }
        
        if (PrecioTF0.getText().equals("")) {
            PrecioTF0.setBackground(Color.pink);
            }else{
            PrecioTF0.setBackground(Color.WHITE);
            dataFactura.precioTF0 = PrecioTF0.getText();    
        }
         
        if (PrecioTF1.getText().equals("")) {
            PrecioTF1.setBackground(Color.pink);
            }else{
            PrecioTF1.setBackground(Color.white);
            dataFactura.precioTF1 = PrecioTF1.getText();
        }
        
        if (PrecioTF2.getText().equals("")) {
            PrecioTF2.setBackground(Color.pink);
            }else{
            PrecioTF2.setBackground(Color.white);
            dataFactura.precioTF2 = PrecioTF2.getText();
         }
        
        if (PrecioTF3.getText().equals("")) {
            PrecioTF3.setBackground(Color.pink);
            }else{
            PrecioTF3.setBackground(Color.white);
            dataFactura.precioTF3 = PrecioTF3.getText();
         }
        
        if (ObservacionesTF.getText().equals("")) {
            ObservacionesTF.setBackground(Color.pink);
            }else{
            ObservacionesTF.setBackground(Color.white);
            dataFactura.observacionesTF = ObservacionesTF.getText();
            }
        //Condicion para poder guardar. Campos obligatorios.
        if ( CiudadTF.getText().equals("") && CpTF.getText().equals("")
                && CalleTF.getText().equals("") && ApellidosTF.getText().equals("") 
                && NombreTF.getText().equals("") && NfacturaTF.getText().equals("") 
                && ConseptoTF0.getText().equals("") && PrecioTF1.getText().equals("")
            ){
            
             MensajeTF.setText("Rellena Todos los campos de color rosa");
            }else{
             //Guardar todos los datos en un archivo CSV
            Temp guardar = new Temp();
            guardar.guardarFactura(dataFactura.getFacturaCSV());
            MensajeTF.setText("");
                  
             //dispose();
        verFactura NuevaVentana = new verFactura();
        NuevaVentana.setVisible(true);
        
        }  
        }
        
        if (nombreRB.isSelected()) {
            
             ArrayList<Factura> miFacturas = LeerArchivo.leerFacturas("todasFacturas.csv");
             for (Factura miFactura : miFacturas) {
                 
               if (NombreTF.getText().equals(miFactura.nombre)) {
                   
                     NfacturaTF.setText(miFactura.numeroFactura);
               NombreTF.setText(miFactura.nombre);
               ApellidosTF.setText(miFactura.apellidos);
               CalleTF.setText(miFactura.calle);
               CpTF.setText(miFactura.cP);
               CiudadTF.setText(miFactura.ciudad);
               ConseptoTF0.setText(miFactura.conseptoTF0);
               ConseptoTF1.setText(miFactura.conseptoTF1);
               ConseptoTF2.setText(miFactura.conseptoTF2);
               ConseptoTF3.setText(miFactura.conseptoTF3);
               PrecioTF0.setText(miFactura.precioTF0);
               PrecioTF1.setText(miFactura.precioTF1);
               PrecioTF2.setText(miFactura.precioTF2);
               PrecioTF3.setText(miFactura.precioTF3);
               ObservacionesTF.setText(miFactura.observacionesTF);
               break;
               }
            } 
              Factura dataFactura = new Factura();
        //condiciones de texto en blanco
        //Recojer datos de todos los campos de texto
         if (NfacturaTF.getText().equals("")) {
            NfacturaTF.setBackground(Color.pink);
            }else{
            NfacturaTF.setBackground(Color.WHITE);
            dataFactura.numeroFactura = NfacturaTF.getText();
        }
         
        if (NombreTF.getText().equals("")) {
            NombreTF.setBackground(Color.pink);
            }else{
            NombreTF.setBackground(Color.WHITE);
            dataFactura.nombre = NombreTF.getText();
        }
        
        if (ApellidosTF.getText().equals("")) {
            ApellidosTF.setBackground(Color.pink);
            }else{
            ApellidosTF.setBackground(Color.WHITE);
            dataFactura.apellidos = ApellidosTF.getText();
        }
        
        if (CalleTF.getText().equals("")) {
            CalleTF.setBackground(Color.pink);
            }else{
            CalleTF.setBackground(Color.WHITE);
            dataFactura.calle = CalleTF.getText();
        }
         
        if (CpTF.getText().equals("")) {
            CpTF.setBackground(Color.pink);
            }else{
            CpTF.setBackground(Color.WHITE);
            dataFactura.cP = CpTF.getText();
        }
         
        if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
        
         if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
         
         if (ConseptoTF0.getText().equals("")) {
            ConseptoTF0.setBackground(Color.pink);
            }else{
            ConseptoTF0.setBackground(Color.WHITE);
            dataFactura.conseptoTF0 = ConseptoTF0.getText();
        }
         
         if (ConseptoTF1.getText().equals("")) {
            ConseptoTF1.setBackground(Color.pink);
            }else{
            ConseptoTF1.setBackground(Color.WHITE);
            dataFactura.conseptoTF1 = ConseptoTF1.getText();
        }
         
        if (ConseptoTF2.getText().equals("")) {
            ConseptoTF2.setBackground(Color.pink);
            }else{
            ConseptoTF2.setBackground(Color.WHITE);
            dataFactura.conseptoTF2 = ConseptoTF2.getText();
        }
        
         if (ConseptoTF3.getText().equals("")) {
            ConseptoTF3.setBackground(Color.pink);
            }else{
            ConseptoTF3.setBackground(Color.WHITE);
            dataFactura.conseptoTF3 = ConseptoTF3.getText();
        }
        
        if (PrecioTF0.getText().equals("")) {
            PrecioTF0.setBackground(Color.pink);
            }else{
            PrecioTF0.setBackground(Color.WHITE);
            dataFactura.precioTF0 = PrecioTF0.getText();    
        }
         
        if (PrecioTF1.getText().equals("")) {
            PrecioTF1.setBackground(Color.pink);
            }else{
            PrecioTF1.setBackground(Color.white);
            dataFactura.precioTF1 = PrecioTF1.getText();
        }
        
        if (PrecioTF2.getText().equals("")) {
            PrecioTF2.setBackground(Color.pink);
            }else{
            PrecioTF2.setBackground(Color.white);
            dataFactura.precioTF2 = PrecioTF2.getText();
         }
        
        if (PrecioTF3.getText().equals("")) {
            PrecioTF3.setBackground(Color.pink);
            }else{
            PrecioTF3.setBackground(Color.white);
            dataFactura.precioTF3 = PrecioTF3.getText();
         }
        
        if (ObservacionesTF.getText().equals("")) {
            ObservacionesTF.setBackground(Color.pink);
            }else{
            ObservacionesTF.setBackground(Color.white);
            dataFactura.observacionesTF = ObservacionesTF.getText();
            }
        //Condicion para poder guardar. Campos obligatorios.
        if ( CiudadTF.getText().equals("") && CpTF.getText().equals("")
                && CalleTF.getText().equals("") && ApellidosTF.getText().equals("") 
                && NombreTF.getText().equals("") && NfacturaTF.getText().equals("") 
                && ConseptoTF0.getText().equals("") && PrecioTF1.getText().equals("")
            ){
            
             MensajeTF.setText("Rellena Todos los campos de color rosa");
            }else{
             //Guardar todos los datos en un archivo CSV
            Temp guardar = new Temp();
            guardar.guardarFactura(dataFactura.getFacturaCSV());
            MensajeTF.setText("");
                  
             //dispose();
        verFactura NuevaVentana = new verFactura();
        NuevaVentana.setVisible(true);
        
        } 
        }
        
            
        
    }//GEN-LAST:event_BuscarFacturaActionPerformed

    private void ConseptoTF0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConseptoTF0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConseptoTF0ActionPerformed

    private void GuardarFacturaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarFacturaMenuActionPerformed

        
        
        Factura dataFactura = new Factura();
        //condiciones de texto en blanco
        //Recojer datos de todos los campos de texto
         if (NfacturaTF.getText().equals("")) {
            NfacturaTF.setBackground(Color.pink);
            }else{
            NfacturaTF.setBackground(Color.WHITE);
            dataFactura.numeroFactura = NfacturaTF.getText();
        }
         
        if (NombreTF.getText().equals("")) {
            NombreTF.setBackground(Color.pink);
            }else{
            NombreTF.setBackground(Color.WHITE);
            dataFactura.nombre = NombreTF.getText();
        }
        
        if (ApellidosTF.getText().equals("")) {
            ApellidosTF.setBackground(Color.pink);
            }else{
            ApellidosTF.setBackground(Color.WHITE);
            dataFactura.apellidos = ApellidosTF.getText();
        }
        
        if (CalleTF.getText().equals("")) {
            CalleTF.setBackground(Color.pink);
            }else{
            CalleTF.setBackground(Color.WHITE);
            dataFactura.calle = CalleTF.getText();
        }
         
        if (CpTF.getText().equals("")) {
            CpTF.setBackground(Color.pink);
            }else{
            CpTF.setBackground(Color.WHITE);
            dataFactura.cP = CpTF.getText();
        }
         
        if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
        
         if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
         
         if (ConseptoTF0.getText().equals("")) {
            ConseptoTF0.setBackground(Color.pink);
            }else{
            ConseptoTF0.setBackground(Color.WHITE);
            dataFactura.conseptoTF0 = ConseptoTF0.getText();
        }
         
         if (ConseptoTF1.getText().equals("")) {
            ConseptoTF1.setBackground(Color.pink);
            }else{
            ConseptoTF1.setBackground(Color.WHITE);
            dataFactura.conseptoTF1 = ConseptoTF1.getText();
        }
         
        if (ConseptoTF2.getText().equals("")) {
            ConseptoTF2.setBackground(Color.pink);
            }else{
            ConseptoTF2.setBackground(Color.WHITE);
            dataFactura.conseptoTF2 = ConseptoTF2.getText();
        }
        
         if (ConseptoTF3.getText().equals("")) {
            ConseptoTF3.setBackground(Color.pink);
            }else{
            ConseptoTF3.setBackground(Color.WHITE);
            dataFactura.conseptoTF3 = ConseptoTF3.getText();
        }
        
        if (PrecioTF0.getText().equals("")) {
            PrecioTF0.setBackground(Color.pink);
            }else{
            PrecioTF0.setBackground(Color.WHITE);
            dataFactura.precioTF0 = PrecioTF0.getText();    
        }
         
        if (PrecioTF1.getText().equals("")) {
            PrecioTF1.setBackground(Color.pink);
            }else{
            PrecioTF1.setBackground(Color.white);
            dataFactura.precioTF1 = PrecioTF1.getText();
        }
        
        if (PrecioTF2.getText().equals("")) {
            PrecioTF2.setBackground(Color.pink);
            }else{
            PrecioTF2.setBackground(Color.white);
            dataFactura.precioTF2 = PrecioTF2.getText();
         }
        
        if (PrecioTF3.getText().equals("")) {
            PrecioTF3.setBackground(Color.pink);
            }else{
            PrecioTF3.setBackground(Color.white);
            dataFactura.precioTF3 = PrecioTF3.getText();
         }
        
        if (ObservacionesTF.getText().equals("")) {
            ObservacionesTF.setBackground(Color.pink);
            }else{
            ObservacionesTF.setBackground(Color.white);
            dataFactura.observacionesTF = ObservacionesTF.getText();
            }
        //Condicion para poder guardar. Campos obligatorios.
        if ( CiudadTF.getText().equals("") && CpTF.getText().equals("")
                && CalleTF.getText().equals("") && ApellidosTF.getText().equals("") 
                && NombreTF.getText().equals("") && NfacturaTF.getText().equals("") 
                && ConseptoTF0.getText().equals("") && PrecioTF1.getText().equals("")
            ){
            
             MensajeTF.setText("Rellena Todos los campos de color rosa");
            }else{
             //Guardar todos los datos en un archivo CSV
            Guardar guardar = new Guardar();
            guardar.guardarFactura(dataFactura.getFacturaCSV());
            MensajeTF.setText("");
        }              // TODO add your handling code here:
    }//GEN-LAST:event_GuardarFacturaMenuActionPerformed

    private void SalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMenuActionPerformed
    
      JDialog.setDefaultLookAndFeelDecorated(true);
    int response = JOptionPane.showConfirmDialog(Top, "Quieres guardar antes de salir", "Mensaje Importante",
        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
    if (response == JOptionPane.NO_OPTION) {
      
      System.exit(0);
    } else if (response == JOptionPane.YES_OPTION) {
                 Factura dataFactura = new Factura();
        //condiciones de texto en blanco
        //Recojer datos de todos los campos de texto
         if (NfacturaTF.getText().equals("")) {
            NfacturaTF.setBackground(Color.pink);
            }else{
            NfacturaTF.setBackground(Color.WHITE);
            dataFactura.numeroFactura = NfacturaTF.getText();
        }
         
        if (NombreTF.getText().equals("")) {
            NombreTF.setBackground(Color.pink);
            }else{
            NombreTF.setBackground(Color.WHITE);
            dataFactura.nombre = NombreTF.getText();
        }
        
        if (ApellidosTF.getText().equals("")) {
            ApellidosTF.setBackground(Color.pink);
            }else{
            ApellidosTF.setBackground(Color.WHITE);
            dataFactura.apellidos = ApellidosTF.getText();
        }
        
        if (CalleTF.getText().equals("")) {
            CalleTF.setBackground(Color.pink);
            }else{
            CalleTF.setBackground(Color.WHITE);
            dataFactura.calle = CalleTF.getText();
        }
         
        if (CpTF.getText().equals("")) {
            CpTF.setBackground(Color.pink);
            }else{
            CpTF.setBackground(Color.WHITE);
            dataFactura.cP = CpTF.getText();
        }
         
        if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
        
         if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
         
         if (ConseptoTF0.getText().equals("")) {
            ConseptoTF0.setBackground(Color.pink);
            }else{
            ConseptoTF0.setBackground(Color.WHITE);
            dataFactura.conseptoTF0 = ConseptoTF0.getText();
        }
         
         if (ConseptoTF1.getText().equals("")) {
            ConseptoTF1.setBackground(Color.pink);
            }else{
            ConseptoTF1.setBackground(Color.WHITE);
            dataFactura.conseptoTF1 = ConseptoTF1.getText();
        }
         
        if (ConseptoTF2.getText().equals("")) {
            ConseptoTF2.setBackground(Color.pink);
            }else{
            ConseptoTF2.setBackground(Color.WHITE);
            dataFactura.conseptoTF2 = ConseptoTF2.getText();
        }
        
         if (ConseptoTF3.getText().equals("")) {
            ConseptoTF3.setBackground(Color.pink);
            }else{
            ConseptoTF3.setBackground(Color.WHITE);
            dataFactura.conseptoTF3 = ConseptoTF3.getText();
        }
        
        if (PrecioTF0.getText().equals("")) {
            PrecioTF0.setBackground(Color.pink);
            }else{
            PrecioTF0.setBackground(Color.WHITE);
            dataFactura.precioTF0 = PrecioTF0.getText();    
        }
         
        if (PrecioTF1.getText().equals("")) {
            PrecioTF1.setBackground(Color.pink);
            }else{
            PrecioTF1.setBackground(Color.white);
            dataFactura.precioTF1 = PrecioTF1.getText();
        }
        
        if (PrecioTF2.getText().equals("")) {
            PrecioTF2.setBackground(Color.pink);
            }else{
            PrecioTF2.setBackground(Color.white);
            dataFactura.precioTF2 = PrecioTF2.getText();
         }
        
        if (PrecioTF3.getText().equals("")) {
            PrecioTF3.setBackground(Color.pink);
            }else{
            PrecioTF3.setBackground(Color.white);
            dataFactura.precioTF3 = PrecioTF3.getText();
         }
        
        if (ObservacionesTF.getText().equals("")) {
            ObservacionesTF.setBackground(Color.pink);
            }else{
            ObservacionesTF.setBackground(Color.white);
            dataFactura.observacionesTF = ObservacionesTF.getText();
            }
        //Condicion para poder guardar. Campos obligatorios.
        if ( CiudadTF.getText().equals("") && CpTF.getText().equals("")
                && CalleTF.getText().equals("") && ApellidosTF.getText().equals("") 
                && NombreTF.getText().equals("") && NfacturaTF.getText().equals("") 
                && ConseptoTF0.getText().equals("") && PrecioTF1.getText().equals("")
            ){
            
            String multiLineMsg[] = { "Antes de guardar los campos color rosa", " Deven de estar rellenos" };
    JOptionPane pane = new JOptionPane();
    pane.setMessage(multiLineMsg);
    JDialog d = pane.createDialog(Top, "Informacion");
    d.setVisible(true);
   

           
            }else{
             //Guardar todos los datos en un archivo CSV
            Guardar guardar = new Guardar();
            guardar.guardarFactura(dataFactura.getFacturaCSV());
            
            System.exit(0);
        } }        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMenuActionPerformed

    private void LimpiarPantallaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarPantallaMenuActionPerformed
  // TODO add your handling code here:
               NfacturaTF.setText("");
               NombreTF.setText("");
               ApellidosTF.setText("");
               CalleTF.setText("");
               CpTF.setText("");
               CiudadTF.setText("");
               ConseptoTF0.setText("");
               ConseptoTF1.setText("");
               ConseptoTF2.setText("");
               ConseptoTF3.setText("");
               PrecioTF0.setText("");
               PrecioTF1.setText("");
               PrecioTF2.setText("");
               PrecioTF3.setText("");
               ObservacionesTF.setText("");
               
                       // TODO add your handling code here:
    }//GEN-LAST:event_LimpiarPantallaMenuActionPerformed

    private void CargarUltimaFacturaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarUltimaFacturaMenuActionPerformed
 ArrayList<Factura> miFacturas = LeerArchivo.leerFacturas("todasFacturas.csv");


           for (Factura miFactura : miFacturas) {
               NfacturaTF.setText(miFactura.numeroFactura);
               NombreTF.setText(miFactura.nombre);
               ApellidosTF.setText(miFactura.apellidos);
               CalleTF.setText(miFactura.calle);
               CpTF.setText(miFactura.cP);
               CiudadTF.setText(miFactura.ciudad);
               ConseptoTF0.setText(miFactura.conseptoTF0);
               ConseptoTF1.setText(miFactura.conseptoTF1);
               ConseptoTF2.setText(miFactura.conseptoTF2);
               ConseptoTF3.setText(miFactura.conseptoTF3);
               PrecioTF0.setText(miFactura.precioTF0);
               PrecioTF1.setText(miFactura.precioTF1);
               PrecioTF2.setText(miFactura.precioTF2);
               PrecioTF3.setText(miFactura.precioTF3);
               ObservacionesTF.setText(miFactura.observacionesTF);
        
            }         // TODO add your handling code here:
    }//GEN-LAST:event_CargarUltimaFacturaMenuActionPerformed

    private void BuscarMunuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMunuActionPerformed
        // TODO add your handling code here:
       if (nFacturaRB.isSelected()) {
        
             ArrayList<Factura> miFacturas = LeerArchivo.leerFacturas("todasFacturas.csv");
             for (Factura miFactura : miFacturas) {
               if (NfacturaTF.getText().equals(miFactura.numeroFactura)) {
                   
                   
                     NfacturaTF.setText(miFactura.numeroFactura);
               NombreTF.setText(miFactura.nombre);
               ApellidosTF.setText(miFactura.apellidos);
               CalleTF.setText(miFactura.calle);
               CpTF.setText(miFactura.cP);
               CiudadTF.setText(miFactura.ciudad);
               ConseptoTF0.setText(miFactura.conseptoTF0);
               ConseptoTF1.setText(miFactura.conseptoTF1);
               ConseptoTF2.setText(miFactura.conseptoTF2);
               ConseptoTF3.setText(miFactura.conseptoTF3);
               PrecioTF0.setText(miFactura.precioTF0);
               PrecioTF1.setText(miFactura.precioTF1);
               PrecioTF2.setText(miFactura.precioTF2);
               PrecioTF3.setText(miFactura.precioTF3);
               ObservacionesTF.setText(miFactura.observacionesTF);
               break;
               
               } 
               
            }   
        
        Factura dataFactura = new Factura();
        //condiciones de texto en blanco
        //Recojer datos de todos los campos de texto
         if (NfacturaTF.getText().equals("")) {
            NfacturaTF.setBackground(Color.pink);
            }else{
            NfacturaTF.setBackground(Color.WHITE);
            dataFactura.numeroFactura = NfacturaTF.getText();
        }
         
        if (NombreTF.getText().equals("")) {
            NombreTF.setBackground(Color.pink);
            }else{
            NombreTF.setBackground(Color.WHITE);
            dataFactura.nombre = NombreTF.getText();
        }
        
        if (ApellidosTF.getText().equals("")) {
            ApellidosTF.setBackground(Color.pink);
            }else{
            ApellidosTF.setBackground(Color.WHITE);
            dataFactura.apellidos = ApellidosTF.getText();
        }
        
        if (CalleTF.getText().equals("")) {
            CalleTF.setBackground(Color.pink);
            }else{
            CalleTF.setBackground(Color.WHITE);
            dataFactura.calle = CalleTF.getText();
        }
         
        if (CpTF.getText().equals("")) {
            CpTF.setBackground(Color.pink);
            }else{
            CpTF.setBackground(Color.WHITE);
            dataFactura.cP = CpTF.getText();
        }
         
        if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
        
         if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
         
         if (ConseptoTF0.getText().equals("")) {
            ConseptoTF0.setBackground(Color.pink);
            }else{
            ConseptoTF0.setBackground(Color.WHITE);
            dataFactura.conseptoTF0 = ConseptoTF0.getText();
        }
         
         if (ConseptoTF1.getText().equals("")) {
            ConseptoTF1.setBackground(Color.pink);
            }else{
            ConseptoTF1.setBackground(Color.WHITE);
            dataFactura.conseptoTF1 = ConseptoTF1.getText();
        }
         
        if (ConseptoTF2.getText().equals("")) {
            ConseptoTF2.setBackground(Color.pink);
            }else{
            ConseptoTF2.setBackground(Color.WHITE);
            dataFactura.conseptoTF2 = ConseptoTF2.getText();
        }
        
         if (ConseptoTF3.getText().equals("")) {
            ConseptoTF3.setBackground(Color.pink);
            }else{
            ConseptoTF3.setBackground(Color.WHITE);
            dataFactura.conseptoTF3 = ConseptoTF3.getText();
        }
        
        if (PrecioTF0.getText().equals("")) {
            PrecioTF0.setBackground(Color.pink);
            }else{
            PrecioTF0.setBackground(Color.WHITE);
            dataFactura.precioTF0 = PrecioTF0.getText();    
        }
         
        if (PrecioTF1.getText().equals("")) {
            PrecioTF1.setBackground(Color.pink);
            }else{
            PrecioTF1.setBackground(Color.white);
            dataFactura.precioTF1 = PrecioTF1.getText();
        }
        
        if (PrecioTF2.getText().equals("")) {
            PrecioTF2.setBackground(Color.pink);
            }else{
            PrecioTF2.setBackground(Color.white);
            dataFactura.precioTF2 = PrecioTF2.getText();
         }
        
        if (PrecioTF3.getText().equals("")) {
            PrecioTF3.setBackground(Color.pink);
            }else{
            PrecioTF3.setBackground(Color.white);
            dataFactura.precioTF3 = PrecioTF3.getText();
         }
        
        if (ObservacionesTF.getText().equals("")) {
            ObservacionesTF.setBackground(Color.pink);
            }else{
            ObservacionesTF.setBackground(Color.white);
            dataFactura.observacionesTF = ObservacionesTF.getText();
            }
        //Condicion para poder guardar. Campos obligatorios.
        if ( CiudadTF.getText().equals("") && CpTF.getText().equals("")
                && CalleTF.getText().equals("") && ApellidosTF.getText().equals("") 
                && NombreTF.getText().equals("") && NfacturaTF.getText().equals("") 
                && ConseptoTF0.getText().equals("") && PrecioTF1.getText().equals("")
            ){
            
             MensajeTF.setText("Rellena Todos los campos de color rosa");
            }else{
             //Guardar todos los datos en un archivo CSV
            Temp guardar = new Temp();
            guardar.guardarFactura(dataFactura.getFacturaCSV());
            MensajeTF.setText("");
                  
             //dispose();
        verFactura NuevaVentana = new verFactura();
        NuevaVentana.setVisible(true);
        
        }  
        }
        
        if (nombreRB.isSelected()) {
            
             ArrayList<Factura> miFacturas = LeerArchivo.leerFacturas("todasFacturas.csv");
             for (Factura miFactura : miFacturas) {
                 
               if (NombreTF.getText().equals(miFactura.nombre)) {
                   
                     NfacturaTF.setText(miFactura.numeroFactura);
               NombreTF.setText(miFactura.nombre);
               ApellidosTF.setText(miFactura.apellidos);
               CalleTF.setText(miFactura.calle);
               CpTF.setText(miFactura.cP);
               CiudadTF.setText(miFactura.ciudad);
               ConseptoTF0.setText(miFactura.conseptoTF0);
               ConseptoTF1.setText(miFactura.conseptoTF1);
               ConseptoTF2.setText(miFactura.conseptoTF2);
               ConseptoTF3.setText(miFactura.conseptoTF3);
               PrecioTF0.setText(miFactura.precioTF0);
               PrecioTF1.setText(miFactura.precioTF1);
               PrecioTF2.setText(miFactura.precioTF2);
               PrecioTF3.setText(miFactura.precioTF3);
               ObservacionesTF.setText(miFactura.observacionesTF);
               break;
               }
            } 
              Factura dataFactura = new Factura();
        //condiciones de texto en blanco
        //Recojer datos de todos los campos de texto
         if (NfacturaTF.getText().equals("")) {
            NfacturaTF.setBackground(Color.pink);
            }else{
            NfacturaTF.setBackground(Color.WHITE);
            dataFactura.numeroFactura = NfacturaTF.getText();
        }
         
        if (NombreTF.getText().equals("")) {
            NombreTF.setBackground(Color.pink);
            }else{
            NombreTF.setBackground(Color.WHITE);
            dataFactura.nombre = NombreTF.getText();
        }
        
        if (ApellidosTF.getText().equals("")) {
            ApellidosTF.setBackground(Color.pink);
            }else{
            ApellidosTF.setBackground(Color.WHITE);
            dataFactura.apellidos = ApellidosTF.getText();
        }
        
        if (CalleTF.getText().equals("")) {
            CalleTF.setBackground(Color.pink);
            }else{
            CalleTF.setBackground(Color.WHITE);
            dataFactura.calle = CalleTF.getText();
        }
         
        if (CpTF.getText().equals("")) {
            CpTF.setBackground(Color.pink);
            }else{
            CpTF.setBackground(Color.WHITE);
            dataFactura.cP = CpTF.getText();
        }
         
        if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
        
         if (CiudadTF.getText().equals("")) {
            CiudadTF.setBackground(Color.pink);
            }else{
            CiudadTF.setBackground(Color.WHITE);
            dataFactura.ciudad = CiudadTF.getText();
        }
         
         if (ConseptoTF0.getText().equals("")) {
            ConseptoTF0.setBackground(Color.pink);
            }else{
            ConseptoTF0.setBackground(Color.WHITE);
            dataFactura.conseptoTF0 = ConseptoTF0.getText();
        }
         
         if (ConseptoTF1.getText().equals("")) {
            ConseptoTF1.setBackground(Color.pink);
            }else{
            ConseptoTF1.setBackground(Color.WHITE);
            dataFactura.conseptoTF1 = ConseptoTF1.getText();
        }
         
        if (ConseptoTF2.getText().equals("")) {
            ConseptoTF2.setBackground(Color.pink);
            }else{
            ConseptoTF2.setBackground(Color.WHITE);
            dataFactura.conseptoTF2 = ConseptoTF2.getText();
        }
        
         if (ConseptoTF3.getText().equals("")) {
            ConseptoTF3.setBackground(Color.pink);
            }else{
            ConseptoTF3.setBackground(Color.WHITE);
            dataFactura.conseptoTF3 = ConseptoTF3.getText();
        }
        
        if (PrecioTF0.getText().equals("")) {
            PrecioTF0.setBackground(Color.pink);
            }else{
            PrecioTF0.setBackground(Color.WHITE);
            dataFactura.precioTF0 = PrecioTF0.getText();    
        }
         
        if (PrecioTF1.getText().equals("")) {
            PrecioTF1.setBackground(Color.pink);
            }else{
            PrecioTF1.setBackground(Color.white);
            dataFactura.precioTF1 = PrecioTF1.getText();
        }
        
        if (PrecioTF2.getText().equals("")) {
            PrecioTF2.setBackground(Color.pink);
            }else{
            PrecioTF2.setBackground(Color.white);
            dataFactura.precioTF2 = PrecioTF2.getText();
         }
        
        if (PrecioTF3.getText().equals("")) {
            PrecioTF3.setBackground(Color.pink);
            }else{
            PrecioTF3.setBackground(Color.white);
            dataFactura.precioTF3 = PrecioTF3.getText();
         }
        
        if (ObservacionesTF.getText().equals("")) {
            ObservacionesTF.setBackground(Color.pink);
            }else{
            ObservacionesTF.setBackground(Color.white);
            dataFactura.observacionesTF = ObservacionesTF.getText();
            }
        //Condicion para poder guardar. Campos obligatorios.
        if ( CiudadTF.getText().equals("") && CpTF.getText().equals("")
                && CalleTF.getText().equals("") && ApellidosTF.getText().equals("") 
                && NombreTF.getText().equals("") && NfacturaTF.getText().equals("") 
                && ConseptoTF0.getText().equals("") && PrecioTF1.getText().equals("")
            ){
            
             MensajeTF.setText("Rellena Todos los campos de color rosa");
            }else{
             //Guardar todos los datos en un archivo CSV
            Temp guardar = new Temp();
            guardar.guardarFactura(dataFactura.getFacturaCSV());
            MensajeTF.setText("");
                  
             //dispose();
        verFactura NuevaVentana = new verFactura();
        NuevaVentana.setVisible(true);
        
        } 
        }
        
            
    }//GEN-LAST:event_BuscarMunuActionPerformed

    private void nFacturaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nFacturaRBActionPerformed

        
        // TODO add your handling code here:
        if (nFacturaRB.isSelected()) {
            BuscarFactura.setEnabled(true);
            BuscarMunu.setEnabled(true);
        }else{
        BuscarFactura.setEnabled(false);
        BuscarMunu.setEnabled(false);
        }
    }//GEN-LAST:event_nFacturaRBActionPerformed

    private void nombreRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRBActionPerformed

        // TODO add your handling code here:
          if (nombreRB.isSelected()) {
            BuscarFactura.setEnabled(true);
            BuscarMunu.setEnabled(true);
        }else{
        BuscarFactura.setEnabled(false);
        BuscarMunu.setEnabled(false);
        }
    }//GEN-LAST:event_nombreRBActionPerformed

    /**
     * @param rgs the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContabilidadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContabilidadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContabilidadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContabilidadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContabilidadGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosTF;
    private javax.swing.JButton BuscarFactura;
    private javax.swing.JMenuItem BuscarMunu;
    private javax.swing.JTextField CalleTF;
    private javax.swing.JMenuItem CargarUltimaFacturaMenu;
    private javax.swing.JTextField CiudadTF;
    private javax.swing.JTextField ConseptoTF0;
    private javax.swing.JTextField ConseptoTF1;
    private javax.swing.JTextField ConseptoTF2;
    private javax.swing.JTextField ConseptoTF3;
    private javax.swing.JLabel ConseptoTl;
    private javax.swing.JTextField CpTF;
    private javax.swing.JLabel ErrorTL;
    private javax.swing.JMenuItem GuardarFacturaMenu;
    private javax.swing.JButton GuardarTodo;
    private javax.swing.JMenuItem LimpiarPantallaMenu;
    private javax.swing.JLabel MensajeTF;
    private javax.swing.JLabel Nfactura;
    private javax.swing.JTextField NfacturaTF;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreTF;
    private javax.swing.JTextArea ObservacionesTF;
    private javax.swing.JLabel PrecioTF;
    private javax.swing.JTextField PrecioTF0;
    private javax.swing.JTextField PrecioTF1;
    private javax.swing.JTextField PrecioTF2;
    private javax.swing.JTextField PrecioTF3;
    private javax.swing.JButton Salir;
    private javax.swing.JMenuItem SalirMenu;
    private javax.swing.JLabel Top;
    private javax.swing.JButton VerFacturaCompleta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JRadioButton nFacturaRB;
    private javax.swing.JRadioButton nombreRB;
    // End of variables declaration//GEN-END:variables
}
