
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class verFactura extends javax.swing.JFrame {

    /**
     * Creates new form FacturaCompleta
     */
    public verFactura() {
        initComponents();
        
        ArrayList<Factura> miFacturas = LeerArchivo.leerFacturas("Temp.csv");


           for (Factura miFactura : miFacturas) {
               NumeroFacturaTF.setText("NuFactura:  "+miFactura.numeroFactura);
               NombreTF.setText       ("Nombre:     "+miFactura.nombre);
               ApellidosTF.setText    ("Apellidos:   "+miFactura.apellidos);
               CalleTF.setText        ("Calle:         "+miFactura.calle+"     CP.: "+miFactura.cP);
               CiudadTF.setText       ("Ciudad:      "+miFactura.ciudad);
             
               ConseptoTF0.setText(miFactura.conseptoTF0);
               PrecioTF0.setText(miFactura.precioTF0);
        
               ConseptoTF1.setText(miFactura.conseptoTF1);
               PrecioTF1.setText(miFactura.precioTF1);
               
               ConseptoTF2.setText(miFactura.conseptoTF2);
               PrecioTF2.setText(miFactura.precioTF2);
                
               ConseptoTF3.setText(miFactura.conseptoTF3);
               PrecioTF3.setText(miFactura.precioTF3);
               ObservacionesTF.setText(miFactura.observacionesTF); 
               
               
             
               Total.setText("TOTAL: ");
           }
        
      
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumeroFacturaTF = new javax.swing.JLabel();
        NombreTF = new javax.swing.JLabel();
        ApellidosTF = new javax.swing.JLabel();
        CalleTF = new javax.swing.JLabel();
        CiudadTF = new javax.swing.JLabel();
        infoBaraNegra = new javax.swing.JLabel();
        ConseptoTF0 = new javax.swing.JLabel();
        PrecioTF0 = new javax.swing.JLabel();
        ConseptoTF1 = new javax.swing.JLabel();
        PrecioTF1 = new javax.swing.JLabel();
        ConseptoTF2 = new javax.swing.JLabel();
        PrecioTF2 = new javax.swing.JLabel();
        ConseptoTF3 = new javax.swing.JLabel();
        PrecioTF3 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        ObservacionesTF = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FondoFactura = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Factura Completa");
        setBounds(new java.awt.Rectangle(525, 23, 576, 650));
        setMinimumSize(new java.awt.Dimension(576, 650));
        setSize(new java.awt.Dimension(576, 650));
        getContentPane().setLayout(null);

        NumeroFacturaTF.setForeground(new java.awt.Color(0, 0, 0));
        NumeroFacturaTF.setText("Numero Factura:");
        getContentPane().add(NumeroFacturaTF);
        NumeroFacturaTF.setBounds(30, 110, 230, 16);

        NombreTF.setForeground(new java.awt.Color(0, 0, 0));
        NombreTF.setText("Nombre:");
        getContentPane().add(NombreTF);
        NombreTF.setBounds(30, 130, 270, 16);

        ApellidosTF.setForeground(new java.awt.Color(0, 0, 0));
        ApellidosTF.setText("Apellidos:");
        getContentPane().add(ApellidosTF);
        ApellidosTF.setBounds(30, 150, 380, 16);

        CalleTF.setForeground(new java.awt.Color(0, 0, 0));
        CalleTF.setText("Calle:");
        getContentPane().add(CalleTF);
        CalleTF.setBounds(30, 170, 370, 16);

        CiudadTF.setForeground(new java.awt.Color(0, 0, 0));
        CiudadTF.setText("Ciudad:");
        getContentPane().add(CiudadTF);
        CiudadTF.setBounds(30, 190, 250, 16);

        infoBaraNegra.setForeground(new java.awt.Color(255, 255, 255));
        infoBaraNegra.setText("Consepto                                                                                        Precio");
        getContentPane().add(infoBaraNegra);
        infoBaraNegra.setBounds(30, 250, 520, 16);

        ConseptoTF0.setForeground(new java.awt.Color(0, 0, 0));
        ConseptoTF0.setText("Concepto Vasillo");
        getContentPane().add(ConseptoTF0);
        ConseptoTF0.setBounds(30, 280, 400, 16);

        PrecioTF0.setForeground(new java.awt.Color(0, 0, 0));
        PrecioTF0.setText("0.00");
        getContentPane().add(PrecioTF0);
        PrecioTF0.setBounds(440, 280, 110, 16);

        ConseptoTF1.setForeground(new java.awt.Color(0, 0, 0));
        ConseptoTF1.setText("Concepto Vasillo");
        getContentPane().add(ConseptoTF1);
        ConseptoTF1.setBounds(30, 310, 400, 16);

        PrecioTF1.setForeground(new java.awt.Color(0, 0, 0));
        PrecioTF1.setText("0.00");
        getContentPane().add(PrecioTF1);
        PrecioTF1.setBounds(440, 310, 110, 16);

        ConseptoTF2.setForeground(new java.awt.Color(0, 0, 0));
        ConseptoTF2.setText("Concepto Vasillo");
        getContentPane().add(ConseptoTF2);
        ConseptoTF2.setBounds(30, 340, 400, 16);

        PrecioTF2.setForeground(new java.awt.Color(0, 0, 0));
        PrecioTF2.setText("0.00");
        getContentPane().add(PrecioTF2);
        PrecioTF2.setBounds(440, 340, 110, 16);

        ConseptoTF3.setForeground(new java.awt.Color(0, 0, 0));
        ConseptoTF3.setText("Concepto Vasillo");
        getContentPane().add(ConseptoTF3);
        ConseptoTF3.setBounds(30, 370, 400, 16);

        PrecioTF3.setForeground(new java.awt.Color(0, 0, 0));
        PrecioTF3.setText("0.00");
        getContentPane().add(PrecioTF3);
        PrecioTF3.setBounds(440, 370, 28, 16);

        Total.setForeground(new java.awt.Color(0, 0, 0));
        Total.setText("TOTAL:");
        getContentPane().add(Total);
        Total.setBounds(380, 520, 170, 30);

        ObservacionesTF.setForeground(new java.awt.Color(51, 51, 51));
        ObservacionesTF.setText("Observaciones");
        getContentPane().add(ObservacionesTF);
        ObservacionesTF.setBounds(30, 400, 520, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apple100x100.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 10, 100, 110);

        FondoFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondoFactura00.png"))); // NOI18N
        getContentPane().add(FondoFactura);
        FondoFactura.setBounds(0, 0, 576, 640);

        jMenuBar1.setToolTipText("");

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.META_MASK));
        jMenuItem1.setText("Nueva Factura");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.META_MASK));
        jMenuItem2.setText("Imprimir");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_MASK));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        // TODO add your handling code here:
          // TODO add your handling code here:
        //dispose();
        ContabilidadGUI VentanaPrencipal = new ContabilidadGUI();
        VentanaPrencipal.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Factura factura = new Factura();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturaCompleta().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidosTF;
    private javax.swing.JLabel CalleTF;
    private javax.swing.JLabel CiudadTF;
    private javax.swing.JLabel ConseptoTF0;
    private javax.swing.JLabel ConseptoTF1;
    private javax.swing.JLabel ConseptoTF2;
    private javax.swing.JLabel ConseptoTF3;
    private javax.swing.JLabel FondoFactura;
    private javax.swing.JLabel NombreTF;
    private javax.swing.JLabel NumeroFacturaTF;
    private javax.swing.JLabel ObservacionesTF;
    private javax.swing.JLabel PrecioTF0;
    private javax.swing.JLabel PrecioTF1;
    private javax.swing.JLabel PrecioTF2;
    private javax.swing.JLabel PrecioTF3;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel infoBaraNegra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

 
}
